### ISSUE TITLE
NuGet.Build.Tasks use Microsoft.Build.Framework 16.5.0-preview-19606-01

### ISSUE THREAD

**Issue by PercyMummelthey** [adobe/xamarin-acpuserprofile#2]
### Expected Behaviour
Build pipeline runs und the IDE build my project.

### Actual Behaviour
I get an error : NuGet.Build.Tasks 5.6.0 depends on Microsoft.Build.Framework (>= 16.5.0-preview-19606-01) but Microsoft.Build.Framework 16.5.0-preview-19606-01 was not found

#### Steps to Reproduce
install this package und try to install another package.
Is it important to use the NuGet.Build.Tasks package inside the acpuserprofile package? The iOS version of this package dont use this NuGet. If its important maybe you can update the version of NuGet.Build.Tasks? This may fix the problem.

#### Platform and Version
its a droid project and i cant build (target version 12)

#### Logs taken while reproducing problem
Package restore failed. Rolling back package changes for 'MyProject.Droid'.
NuGet.Build.Tasks 5.6.0 depends on Microsoft.Build.Framework (>= 16.5.0-preview-19606-01) but Microsoft.Build.Framework 16.5.0-preview-19606-01 was not found. An approximate best match of Microsoft.Build.Framework 16.5.0  ... icrosoft.Build.Tasks.Core 16.5.0 was resolved.
NuGet.Build.Tasks 5.6.0 depends on Microsoft.Build.Utilities.Core (>= 16.5.0-preview-19606-01) but Microsoft.Build.Utilities.Core 16.5.0-preview-19606-01 was not found. An approximate best match of Microsoft.Build.Utilities.Core 16.5.0 was resolved.

**Comment by PercyMummelthey** [comment]
Or maybe set NuGet.Build.Tasks to <PrivateAssets>all</PrivateAssets>

**Comment by casmj** [comment]
Hi Percy, thanks for bringing this to our attention - and for the great detail! We're looking into this problem, and we'll likely have it resolved by early next year.

**Comment by cacheung** [comment]
@PercyMummelthey 
We just released Adobe.ACPUserProfile.Android version 1.0.0, please check to see if it resolves the issue.

**Comment by cacheung** [comment]
Closing the issue.  Please open a new issue if there is any question.
