### ISSUE TITLE
AssemblyName attribute of iOS library has ambiguous value

### ISSUE THREAD

**Issue by raginmari** [adobe/xamarin-acpuserprofile#3]
### Expected Behaviour

When I use both Adobe.AEPAssurance.iOS and Adobe.ACPUserProfile.iOS in my project, both libraries are available to me and work as expected.

### Actual Behaviour

When I use both Adobe.AEPAssurance.iOS and Adobe.ACPUserProfile.iOS in my project, NuGet discards the one with the lower version number because both libraries compile to "NativeLibrary.dll".

### Reproduce Scenario (including but not limited to)

Every build of iOS projects using both Adobe.AEPAssurance.iOS and Adobe.ACPUserProfile.iOS.

#### Steps to Reproduce

- Create new Xamarin.Forms project
- Add NuGet Adobe.AEPAssurance.iOS to iOS platform project
- Add NuGet Adobe.ACPUserProfile.iOS to iOS platform project
- Probably reference both in your code
- Build iOS project

#### Platform and Version

- Xamarin.Forms for iOS
- Adobe.AEPAssurance.iOS 1.0.0
- Adobe.ACPUserProfile.iOS 0.0.2

#### Sample Code that illustrates the problem

I cannot post any actual code, I'm afraid.

#### Logs taken while reproducing problem

Encountered conflict between 'Reference:/Users/XXX/.nuget/packages/adobe.acpuserprofile.ios/0.0.2/lib/xamarinios10/NativeLibrary.dll' and 'Reference:/Users/XXX/.nuget/packages/adobe.aepassurance.ios/1.0.0/lib/xamarinios10/NativeLibrary.dll'. Choosing 'Reference:/Users/XXX/.nuget/packages/adobe.aepassurance.ios/1.0.0/lib/xamarinios10/NativeLibrary.dll' because AssemblyVersion '1.0.0.0' is greater than '0.0.2.0'.

**Comment by cacheung** [comment]
The ACPUserProfile hasn't been updated to iOS 1.0.0 version which could be the reason why not working with Assurance 1.0.0.  We will look into this.

**Comment by cacheung** [comment]
@raginmari do you need User Profile features for your project?  If not, you can remove it as a workaround for now.

**Comment by raginmari** [comment]
We need both Assurance and User Profile in our project. The issue is that the assembly name of both libraries is [defined as "NativeLibrary"](https://github.com/adobe/xamarin-acpuserprofile/blob/master/src/Adobe.ACPUserProfile.iOS/Adobe.ACPUserProfile.iOS.csproj#L12). NuGet will resolve this conflict and discard one of the libraries.

**Comment by cacheung** [comment]
@raginmari thanks for the info. We are looking into this.

**Comment by cacheung** [comment]
@raginmari 
We just released Adobe.ACPUserProfile.iOS (1.0.0), please let us know if it resolves this issue.

**Comment by cacheung** [comment]
Closing the issue.  Please open a new issue if there is any question.
